---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: docamole-com
  namespace: docamole
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: docamole.com
  dnsNames:
  - www.docamole.com
  - docamole.com
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - www.docamole.com
      - docamole.com
