---
apiVersion: v1
kind: Namespace
metadata:
  name: docamole
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docamole-config
  namespace: docamole
data:
  redis.host: "redis://redis.docamole.svc.cluster.local"
  db.host: "127.0.0.1"
  db.port: "5432"
