---
apiVersion: v1
kind: Namespace
metadata:
  name: {{service.namespace}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{build.name}}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{build.name}}
  namespace: {{service.namespace}}
spec:
  selector:
    app: {{build.name}}
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{build.name}}
  namespace: {{service.namespace}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{build.name}}
    spec:
      containers:
      - name: {{build.name}}
        image: redis:5.0.1-alpine3.8
        imagePullPolicy: Always
        ports:
        - name: redis
          containerPort: 6379
